# Default values for Pewpew.
# Update these values according to your requirements.
ingressHost: https://kubernetes.default.svc

pewpew:
  image: sjultra/pewpew
  tag: latest
  httpPort: 80
  targetPort: 8080

adapter:
  image: sjultra/pewpew-adapter
  tag: latest
  schedule: '"0 * * * *"'

pvc:
  mount: pewpew-adapter-volume
  claim: pewpew-adapter-pvc
  name: pewpew-adapter-pv
  tenantId: "YOUR-TENANT-ID"
  clientId: "YOUR-CLIENT-ID"
  clientSecret: "YOUR-CLIENT-SECRET"
